<span class="sign"><a href="https://www.facebook.com/pages/Friend-Selector-Community/495253630504678" target="_blank">About</a> | <a href="http://friend-selector.sakura.ne.jp/releasenote.txt" target="_blank">Release note</a> | <a href="http://friend-selector.sakura.ne.jp/terms_privacy" target="_blank">Terms of Service & Privacy Policy</a><br />Friend Selector Version 1.0.1 Copyright © <a href="http://www.813.co.jp/" target="_blank">81,Inc.</a> Created by <a href="https://www.facebook.com/keiichi.honma2" target="_blank">@Keiichi Honma</a></span>
<script type="text/javascript"
         src="http://connect.facebook.net/en_US/all.js"></script>
<script type="text/JavaScript">
FB.init({ldelim}
    appId: "{$appId}", // edit it
    status: true,
    cookie: true,
    xfbml: true,
    logging: true
{rdelim});

window.fbAsyncInit = function() {ldelim}
    FB.Canvas.setAutoResize();
{rdelim}

jQuery(document).ready(function(){ldelim}
    // hide scroll bar
    FB.Canvas.setAutoResize();
{rdelim});
</script>
