<span class="sign">Copyright © <a href="http://www.813.co.jp/" target="_parent">81,Inc.</a> Created by <a href="https://www.facebook.com/keiichi.honma2" target="_parent">@Keiichi Honma</a>.</span>

<script type="text/javascript"
         src="http://connect.facebook.net/en_US/all.js"></script>
<script type="text/JavaScript">
FB.init({ldelim}
    appId: "{$appId}", // edit it
    status: true,
    cookie: true,
    xfbml: true,
    logging: true
{rdelim});

window.fbAsyncInit = function() {ldelim}
    FB.Canvas.setAutoResize();
{rdelim}

jQuery(document).ready(function(){ldelim}
    // hide scroll bar
    FB.Canvas.setAutoResize();
{rdelim});
</script>
